-- Vaatz 일반_입찰현황

/* 작성자 : 이소진
 * 작업내역 : 2025.05.14 최초 작성
 * 
 * DB Connection : VAATZ_GPMSDB
 * 
 * [Target/Source 앱]
 * Vaatz_03.입찰현황_QVD생성
 * 
 * [Table]
 * TABLE1		가격등록 Batch관련 Temp Table
 * TABLE2		입찰품목상세
 * TABLE3		가격등록 Batch관련 Temp Table
 * TABLE4		자재 MASTER 관리
 * TABLE5		견적서 상세
 * TABLE6		로그 테이블
 * TABLE7		로그 테이블
 * TABLE8		부서정보 관리
 * TABLE9		사용자정보 관리
 * TABLE10		가격등록 Batch관련 Temp Table
 * 
 * */

/*--------------------------------- Data Loading ---------------------------------*/
WITH PMHD AS (
	SELECT  
		   HOUSE_CODE
		 , MATERIAL_CLASS1
		 , MATERIAL_CLASS2
		 , MATERIAL_CLASS3
		 , MATERIAL_CLASS1_LOC
		 , MATERIAL_CLASS2_LOC
		 , MATERIAL_CLASS3_LOC
	FROM COMADM.TABLE6	/* 로그 테이블 */
)
SELECT     
	   F.RFQ_NO AS "입찰번호"
	 , F.RFQ_COUNT AS "차수"
	 , F.VENDOR_CODE AS "업체코드"
	 , F.VENDOR_NAME AS "업체명"
	 , F.VENDOR_CODE || '-' || F.VENDOR_NAME AS "업체코드명"
	 , ( CASE 
    	 WHEN F.BID_FLAG = 'N' THEN '포기'
		 WHEN F.BID_FLAG = 'Y' THEN '응찰'
		 ELSE '미응찰'
		 END ) AS "응찰여부"
	 , F.SETTLE_YN AS "선정여부"
	 , TO_DATE(F.RFQ_DATE,'YYYYMMDD') + INTERVAL '9' HOUR AS "견적의뢰일"			-- Tableau 추출 표준시간대 맞추기 위해 + 9시간
	 , TO_DATE(F.RFQ_CLOSE_DATE,'YYYYMMDD') + INTERVAL '9' HOUR AS "입찰마감일"	-- Tableau 추출 표준시간대 맞추기 위해 + 9시간
	 , F.SUBJECT AS "견적명"
	 , ( CASE WHEN F.RE_RFQ_FLAG = 'P' THEN 'Y' ELSE 'N' END ) AS "자동재입찰여부"
	 , F.RFQ_TYPE AS "견적형태"
	 , F.SETTLE_TYPE AS "낙찰기준"
	 , F.ITEM_NO AS "품번"
	 , F.ITEM_NAME AS "품명"
	 , F.SPECIFICATION AS "규격"
	 , FN_GET_CDNM('KO', 'ALL', 'M820', F.RE_RFQ_MAIN) AS "재입찰유형"
	 , FN_GET_CDNM('KO', 'ALL', 'M367', F.RE_RFQ_FLAG) AS "재입찰구분"
	 , FN_GET_CDNM('KO', 'ALL', 'M366', F.RE_RFQ_TYPE) AS "재입찰발생유형"
	 , F.CANCEL_FLAG AS "입찰취소여부"
	 , FN_GET_CDNM('KO', 'ALL', 'M820', F.CL_RFQ_MAIN) AS "취소유형"
	 , FN_GET_CDNM('KO', 'ALL', 'M367', F.CL_RFQ_FLAG) AS "취소구분"
	 , FN_GET_CDNM('KO', 'ALL', 'M366', F.CL_RFQ_TYPE) AS "취소발생유형"
	 , F.EV_PURCHASE_TYPE AS "전문업체구매유형"
	 , F.EV_MAIN_GROUP AS "전문업체메인그룹"
	 , F.EV_FIRST_GROUP AS "전문업체대분류"
	 , F.EV_SECOND_GROUP AS "전문업체중분류"
	 , F.EV_THIRD_GROUP AS "전문업체소분류"
	 , F.PURCHASE_DEPT_NAME AS "구매부서명"
	 , F.PURCHASER_NAME AS "구매담당명"
	 , NVL(( CASE WHEN F.SETTLE_YN = 'Y' THEN F.SETTLE_AMT ELSE 0 END ),0) AS "낙찰금액"
	 , ( CASE WHEN F.RE_RFQ_FLAG = 'H' THEN 'Y' ELSE 'N' END ) AS "오입력"
	 , 1 AS "Row_Cnt"
FROM (
	SELECT
		   RQHD.COMPANY_CODE AS COMPANY_CODE
		 , RQHD.RFQ_NO AS RFQ_NO
		 , RQHD.SUBJECT AS SUBJECT
		 , FN_GET_CDNM('KO', 'ALL', 'M112', RQHD.RFQ_TYPE) AS RFQ_TYPE
		 , PMHD1.MATERIAL_CLASS1_LOC AS FIRST_GROUP
		 , PMHD2.MATERIAL_CLASS2_LOC AS SECOND_GROUP
		 , PMHD3.MATERIAL_CLASS3_LOC AS THIRD_GROUP
		 , MTGL.ITEM_NO  ITEM_NO
		 , REPLACE( REPLACE( MTGL.DESCRIPTION_LOC, CHR(10), CHR(32) ), CHR(13), CHR(32) ) AS ITEM_NAME
		 , REPLACE( REPLACE( MTGL.SPECIFICATION, CHR(10), CHR(32) ), CHR(13), CHR(32) ) AS SPECIFICATION
		 , RQSE.VENDOR_CODE AS VENDOR_CODE
		 , VNGL.NAME_LOC AS VENDOR_NAME
		 , RQDT.RFQ_COUNT AS RFQ_COUNT
		 , FN_GET_CDNM('KO','ALL','M369',RQHD.SETTLE_TYPE) AS SETTLE_TYPE
		 , RQHD.RE_RFQ_MAIN
		 , RQHD.RE_RFQ_FLAG
		 , RQHD.RE_RFQ_TYPE
		 , RQHD.CL_RFQ_MAIN
		 , RQHD.CL_RFQ_FLAG
		 , RQHD.CL_RFQ_TYPE
		 , DECODE(QTDT.SETTLE_DATE, NULL, 'N', 'Y') AS SETTLE_YN
		 , QTDT.SETTLE_DATE AS SETTLE_DATE
		 , OGDP.NAME_LOC AS PURCHASE_DEPT_NAME
		 , LUSR.USER_NAME_LOC AS PURCHASER_NAME
		 , MTGL.MATERIAL_CLASS3 AS MATERIAL_CLASS3
		 , DECODE(RQDT.PROGRESS, 'CNL', 'Y', 'N') AS CANCEL_FLAG
		 , QTDT.BID_FLAG
		 , RQHD.RFQ_DATE
		 , RQHD.EV_PURCHASE_TYPE
		 , RQHD.EV_MAIN_GROUP
		 , RQHD.EV_FIRST_GROUP
		 , RQHD.EV_SECOND_GROUP
		 , RQHD.EV_THIRD_GROUP
		 , RQHD.RFQ_CLOSE_DATE
		 , ( SELECT DTOADM.FN_GET_EXCH(COMPANY_CODE, HOUSE_CODE, ADD_DATE, CUR, 'KRW', UNIT_PRICE * SETTLE_QTY )                    
			 FROM DTOADM.TABLE10	/* 가격등록 Batch관련 Temp Table */
			 WHERE QTA_NO = QTDT.QTA_NO
			 AND QTA_SEQ = QTDT.QTA_SEQ
			 AND SETTLE_FLAG = 'Y'
			 AND STATUS <> 'D'
             AND ROWNUM = 1
		   ) AS SETTLE_AMT
	FROM (
		SELECT	
			   HOUSE_CODE
			  , COMPANY_CODE
			  , RFQ_NO
			  , RFQ_COUNT
			  , PROGRESS
			  , RFQ_TYPE
			  , RFQ_DATE
			  , SUBJECT
			  , SETTLE_TYPE
			  , RE_RFQ_REMARK
			  , RFQ_CLOSE_DATE
			  , ADD_USER_DEPT
			  , ADD_USER_ID
			  , RE_RFQ_MAIN
			  , RE_RFQ_FLAG
			  , RE_RFQ_TYPE
			  , CL_RFQ_MAIN
			  , CL_RFQ_FLAG
			  , CL_RFQ_TYPE
			  , FN_GET_EV_NAME(COMPANY_CODE, 1, PURCHASE_TYPE)        EV_PURCHASE_TYPE
			  , FN_GET_EV_NAME(COMPANY_CODE, 2, MAIN_GROUP)           EV_MAIN_GROUP
			  , FN_GET_EV_NAME(COMPANY_CODE, 3, FIRST_GROUP)          EV_FIRST_GROUP
			  , FN_GET_EV_NAME(COMPANY_CODE, 4, SECOND_GROUP)         EV_SECOND_GROUP
			  , FN_GET_EV_NAME(COMPANY_CODE, 5, THIRD_GROUP)          EV_THIRD_GROUP
		FROM DTOADM.TABLE1	/* 가격등록 Batch관련 Temp Table */
		WHERE 1=1
		AND HOUSE_CODE = '100'
		AND	COMPANY_CODE IN ('HMC', 'KMC')
		AND RFQ_DATE BETWEEN TO_CHAR(ADD_MONTHS(SYSDATE + INTERVAL '9' HOUR, -61), 'YYYYMMDD') 	-- 최근 5년
						 AND TO_CHAR(SYSDATE + INTERVAL '9' HOUR, 'YYYYMMDD')
		AND	STATUS <> 'D' 
		) RQHD
	INNER JOIN (
		SELECT 
			   HOUSE_CODE
			 , COMPANY_CODE
			 , RFQ_NO
			 , RFQ_COUNT
			 , RFQ_SEQ
			 , ITEM_NO
			 , PROGRESS
		FROM DTOADM.TABLE2	/* 입찰품목상세 */
		WHERE 1=1
		AND	STATUS <> 'D'
		) RQDT
	ON  RQHD.HOUSE_CODE = RQDT.HOUSE_CODE
	AND	FNCOM(RQHD.COMPANY_CODE) = FNCOM(RQDT.COMPANY_CODE)
	AND	RQHD.RFQ_NO = RQDT.RFQ_NO
	AND	RQHD.RFQ_COUNT = RQDT.RFQ_COUNT
	INNER JOIN (
		SELECT 
			   HOUSE_CODE
			 , COMPANY_CODE
			 , RFQ_NO
			 , RFQ_COUNT
			 , RFQ_SEQ
			 , VENDOR_CODE
		FROM DTOADM.TABLE3	/* 가격등록 Batch관련 Temp Table */
		WHERE 1=1
		AND	BID_FLAG IN ('C', 'P')
		)RQSE
	ON  RQDT.HOUSE_CODE = RQSE.HOUSE_CODE
	AND	FNCOM(RQDT.COMPANY_CODE) = FNCOM(RQSE.COMPANY_CODE)
	AND	RQDT.RFQ_NO = RQSE.RFQ_NO
	AND	RQDT.RFQ_COUNT = RQSE.RFQ_COUNT
	AND	RQDT.RFQ_SEQ = RQSE.RFQ_SEQ
	INNER JOIN (
		SELECT
			   HOUSE_CODE
			 , ITEM_NO
			 , MATERIAL_CLASS1
			 , MATERIAL_CLASS2
			 , MATERIAL_CLASS3
			 , DESCRIPTION_LOC
			 , SPECIFICATION
		FROM COMADM.TABLE4	/* 자재 MASTER 관리 */
		)MTGL
	ON  RQDT.HOUSE_CODE = MTGL.HOUSE_CODE
	AND RQDT.ITEM_NO = MTGL.ITEM_NO
	LEFT JOIN (
		SELECT
			   HOUSE_CODE
			 , RFQ_NO
			 , RFQ_COUNT
			 , RFQ_SEQ
			 , VENDOR_CODE
			 , QTA_NO
			 , QTA_SEQ
			 , SETTLE_DATE
			 , BID_FLAG
		FROM DTOADM.TABLE5	/* 견적서 상세 */
		WHERE 1=1
		AND PROGRESS <> 'TMP'
		AND STATUS <> 'D'
		) QTDT
	ON RQSE.HOUSE_CODE = QTDT.HOUSE_CODE
	AND RQSE.RFQ_NO = QTDT.RFQ_NO
	AND RQSE.RFQ_COUNT = QTDT.RFQ_COUNT
	AND RQSE.RFQ_SEQ = QTDT.RFQ_SEQ
	AND RQSE.VENDOR_CODE = QTDT.VENDOR_CODE
	/*------------------------------ 서브쿼리 (TABLE6) -------------------------------*/
	LEFT JOIN (
		SELECT
			   HOUSE_CODE
			 , MATERIAL_CLASS1
			 , MATERIAL_CLASS1_LOC
			 , ROW_NUMBER() OVER (PARTITION BY HOUSE_CODE, MATERIAL_CLASS1 ORDER BY NULL) AS RN
		FROM PMHD
		) PMHD1
	ON  MTGL.HOUSE_CODE = PMHD1.HOUSE_CODE
	AND MTGL.MATERIAL_CLASS1 = PMHD1.MATERIAL_CLASS1
	AND PMHD1.RN = 1
	LEFT JOIN (
		SELECT
			   HOUSE_CODE
			 , MATERIAL_CLASS2
			 , MATERIAL_CLASS2_LOC
			 , ROW_NUMBER() OVER (PARTITION BY HOUSE_CODE, MATERIAL_CLASS2 ORDER BY NULL) AS RN
		FROM PMHD
		) PMHD2
	ON  MTGL.HOUSE_CODE = PMHD2.HOUSE_CODE
	AND MTGL.MATERIAL_CLASS2 = PMHD2.MATERIAL_CLASS2
	AND PMHD2.RN = 1
	LEFT JOIN (
		SELECT
			   HOUSE_CODE
			 , MATERIAL_CLASS3
			 , MATERIAL_CLASS3_LOC
			 , ROW_NUMBER() OVER (PARTITION BY HOUSE_CODE, MATERIAL_CLASS3 ORDER BY NULL) AS RN
		FROM PMHD
		) PMHD3
	ON  MTGL.HOUSE_CODE = PMHD3.HOUSE_CODE
	AND MTGL.MATERIAL_CLASS3 = PMHD3.MATERIAL_CLASS3
	AND PMHD3.RN = 1
	/*------------------------------ 서브쿼리 (TABLE7) -------------------------------*/
	LEFT JOIN (
		SELECT  
			   HOUSE_CODE
			 , VENDOR_CODE
			 , NAME_LOC
			 , ROW_NUMBER() OVER (PARTITION BY HOUSE_CODE, VENDOR_CODE ORDER BY NULL) AS RN
		FROM COMADM.TABLE7	/* 로그 테이블 */
		) VNGL
	ON  RQSE.HOUSE_CODE = VNGL.HOUSE_CODE
	AND RQSE.VENDOR_CODE = VNGL.VENDOR_CODE
	AND VNGL.RN = 1
	/*------------------------------ 서브쿼리 (TABLE8) -------------------------------*/
	LEFT JOIN (
		SELECT  
			   COMPANY_CODE
			 , DEPT
			 , NAME_LOC
			 , ROW_NUMBER() OVER (PARTITION BY COMPANY_CODE, DEPT ORDER BY NULL) AS RN
		FROM COMADM.TABLE8	/* 부서정보 관리 */
		) OGDP
	ON  RQHD.COMPANY_CODE = OGDP.COMPANY_CODE
	AND RQHD.ADD_USER_DEPT = OGDP.DEPT
	AND OGDP.RN = 1
	/*------------------------------ 서브쿼리 (TABLE9) -------------------------------*/
	LEFT JOIN (
		SELECT
			   HOUSE_CODE
			 , USER_ID
			 , USER_NAME_LOC
			 , ROW_NUMBER() OVER (PARTITION BY HOUSE_CODE, USER_ID ORDER BY NULL) AS RN
		FROM COMADM.TABLE9	/* 사용자정보 관리 */
		) LUSR
	ON  RQHD.HOUSE_CODE = LUSR.HOUSE_CODE
	AND RQHD.ADD_USER_ID = LUSR.USER_ID
	AND LUSR.RN = 1
) F`